services:
  mariadb:
    image: mariadb
    context: ./requirements/mariadb
    container_name: mariadb
    networks:
      - wordpress-network
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  networks:
    wordpress-network:

  volumes:
    db-data:
      driver: local
      type: none
      device: /Users/haru/data/db-data
      o: bind

