services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - wordpress-network
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./.env
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - wordpress-network
      - nginx-network
    volumes:
      - wordpress_files:/var/www/html
      - ./requirements/wordpress/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
    env_file:
      - ./.env
    depends_on:
      - mariadb
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    networks:
      - nginx-network
    volumes:
      - wordpress_files:/var/www/html
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/default:/etc/nginx/sites-available/default
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

networks:
  wordpress-network:
  nginx-network:

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/oaoba/data/wordpress_files
      o: bind
  db-data:
    driver: local
    driver_opts:
      type: none
      device: /home/oaoba/data/db-data
      o: bind
